### ISSUE TITLE
changing factoryType to MvcWebRazorHostFactory causing views intellisense errors

### ISSUE THREAD

**Issue by croban** [tompazourek/RazorHtmlMinifier.Mvc5#1]
If i open Visual Studio 2017 solution which has inside configured  
`
<host factoryType="RazorHtmlMinifier.Mvc5.MinifyingMvcWebRazorHostFactory, RazorHtmlMinifier.Mvc5, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null" />`  
inside view/web.config then intellisense does not work correctly.

![image](https://user-images.githubusercontent.com/7048578/34616037-2b376548-f237-11e7-900a-4bae7ed1603c.png)

**Comment by tompazourek** [comment]
Thanks for the report. You're right, I was able to reproduce the issue on my machine as well.

I investigated a bit around this issue, and the solution to this issue is to make the RazorHtmlMinifier.Mvc5 assembly strong-named. I have no idea why VS needs strong-named assemblies there for the intellisense to work, but it apparently does.

So I added the signing support, and [published a new release 1.1.0](https://www.nuget.org/packages/RazorHtmlMinifier.Mvc5/1.1.0), which the assembly has strong-named.

If you update the NuGet package to 1.1.0, you'll need to configure the Web.config file to (version is now `1.1.0.0` and now we have `PublicKeyToken=a517a17e203fcde4`):

```
<host factoryType="RazorHtmlMinifier.Mvc5.MinifyingMvcWebRazorHostFactory, RazorHtmlMinifier.Mvc5, Version=1.1.0.0, Culture=neutral, PublicKeyToken=a517a17e203fcde4" />
```

After changing this, you might need to rebuild and then restart VS for the intellisense to start working again.

Hope this works for you as well, let me know if you try it.

**Comment by croban** [comment]
Hi, unfortunately this fix did not helped, I have installed a new nuget also I have add new settings with publickeytoken, i have clean and rebuild solution, closed VS and reopen it, but that all did not helped :(

**Comment by tompazourek** [comment]
I've tried it again today, and I'm experiencing some issues again too. I swear I had it working yesterday... but I guess that's how it goes sometimes.

I've investigated more and it looks like VS actually needs to have the assembly in GAC for intellisense to work. Luckily, now when the latest version of the library is strong-named, it's possible to add it to GAC. Adding the assembly to GAC shouldn't have any side-effects, but it will need to be added on every developer machine that wants to use see the intellisense in Razor files completely (without the squiggly undelines), which can be a hassle.

If you want to add the assembly to GAC, you'll need to do the following:

- Open `Developer Command Prompt for VS 2017` (you'll find it in Start menu) **as an Administrator**.
- Navigate to the folder of the NuGet package: `cd "C:\PATH_TO_YOUR_SOLUTION\packages\RazorHtmlMinifier.Mvc5.1.1.0\lib\net45"`
- Install it to GAC: `gacutil /i RazorHtmlMinifier.Mvc5.dll` (it should respond `Assembly successfully added to the cache`)
- Restart VS 2017 (and maybe also clear any ReSharper caches if you're using that)

Then it should start working (I've tried it several times, and it's again working for me).

There are also other alternative solutions:

- Set up the host factory in *Web.config.Release* instead of *Web.config*. That will make the minification run only when the Release configs are applied, and while debugging, you can keep the original host factory, which doesn't have problems with intellisense. I don't really use or like the `.Release` and `.Debug` configs, but it should work.
- Set the host factory in the Web.config file in runtime, e.g. in `Global.asax`. You'd have to use the `WebConfigurationManager` API to modify the Web.config during runtime.

However, I wouldn't recommend either of those (I also haven't tried them), as they feel more like a hack, and might cause more issues if you'd be doing stuff like precompilation of the views. Adding the assembly to GAC is probably the easiest (it's still annoying that VS requires that though...)

Another alternative solution I found worked, is just not to use the NuGet package, and just copy the source code to some project (it's MIT licensed). The entire factory is [just a single file](https://github.com/tompazourek/RazorHtmlMinifier.Mvc5/blob/master/src/RazorHtmlMinifier.Mvc5/MinifyingMvcWebRazorHostFactory.cs). And then you can reference a local project containing the source code like [shown in the sample project included in the repo](https://github.com/tompazourek/RazorHtmlMinifier.Mvc5/blob/master/src/RazorHtmlMinifier.Sample/Views/Web.config#L13) (it's the name of the class including all namespaces, comma, and a name of the containing assembly -- the one where you include the source code).

Hope it helps.

**Comment by croban** [comment]
Hi Tom 

I think this is VS Problem, I will ask by MS. For now I've solve it with wpp.targets ;)
Thx

br

**Comment by croban** [comment]
Hi Tom, please vote:
https://developercommunity.visualstudio.com/content/problem/213734/mvc-views-changing-to-custom-factory-cause-intelli.html

**Comment by tompazourek** [comment]
Thanks, I voted.

Right now, I resolve any Intellisense issues by registering the RazorHtmlMinifier.Mvc5 assembly to GAC. It would be great if I didn't have to do that.
